
"zh":
  activerecord:
    attributes:
      user:
        Name:"账号"
        Password:"请设置密码"
        Password confirmation:"请确认密码"
        Password forget question:"忘记密码问题"
        Password forget answer:"忘记密码答案"
    errors:
      models:
        user:
          attributes:
            name:
              blank:"请将注册信息填写完整"
              taken:"该帐号已注册"
            password:
              confirmation:"两次密码输入不一致，请重新输入"
              too_short:"最短%{count}个字符"
            password_digest:
              blank:"请将注册信息填写完整"
            forget_password_question:
              blank:"请将注册信息填写完整"
            forget_password_answer:
              blank:"请将注册信息填写完整"
